include: package:lint/analysis_options.yaml

linter:
  rules:
    sort_pub_dependencies: false
    avoid_dynamic_calls: false

analyzer:
  exclude:
    - lib/**/*.freezed.dart
    - lib/**/*.g.dart

  strong-mode:
    implicit-casts: true

  errors:
    missing_required_param: error
